### ISSUE TITLE
"h5p-nodejs-library": "^6.2.0" update error.

### ISSUE THREAD

**Issue by vietdungiitb** [kiron/h5p-lti-1p0-provider#1]
The application has error "Cannot GET /h5p" when it is updated "h5p-nodejs-library" to "^6.2.0".

**Comment by sr258** [comment]
Note that h5p-nodejs-library has been split up into several packages and has been updated quite a bit: The packages are now available at @lumieducation, e.g. @lumieducation/h5p-server

**Comment by vietdungiitb** [comment]
I will update it.
I have been developing a canvas-lti based on this project. H5p contents can be showed well if I test it standalone. However it has an error: "_**Uncaught DOMException: Blocked a frame with origin "https://ltis.edusuccess.vn" from accessing a cross-origin frame**_" which makes H5P contents not to be presented in LTI iframe. I have tried something with Cors module but no luck.  I really need help to solve it. 
Thanks you,
Brgs.

![error](https://user-images.githubusercontent.com/15527533/119251265-010aaa80-bbd0-11eb-8d79-4bf5f58295eb.png)
![error1](https://user-images.githubusercontent.com/15527533/119251360-58a91600-bbd0-11eb-9146-1ad5f19f9eae.png)

**Comment by sr258** [comment]
We have an internal app that works fine inside an iframe (player & editor). Here's what we did:

In the Express server:
```
import cors from 'cors';
app.use(       
      cors({            
             origin: [                
                     `https://canvas.edusuccess.vn`,
                     `https://lti.eduscuccess.vn`,   
              ],      
       })     
 );
```
This allows cors requests from your two domains. You can also allow all cors requests by using `app.use(cors())`

If you want to display the editor in an iframe, you also have to add this to the client code (run in the browser) BEFORE it loads the H5P stuff:

```
        // Setting this window's parent to itself is hacky, but necessary, as
        // the H5P core files assume that window.parent can be accessed. This is
        // not the case if we run in an environment that lives
        // in a cross-origin iframe and accessing window.parent is NOT allowed 
        // in there. window.parent is designated as read-only, so this might
        // break if browser change their behavior in the future.
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        window.parent = window;
```

If you need the parent window in your own code, you have to save in a different global variable before rewiring it.

Note that we have extended the library significantly since h5p-lti-1p0-provider was created. There now are vanilla HTML 5 webcomponents and React components that you can use to create SPA applications with dynamic component creation. The server-side rendering this repo here still uses does still work, but depending on what you want to do, you might want to have a look at what added in the last few months.

**Comment by vietdungiitb** [comment]
Thank you very much...I will change it to SPA application.
